// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('e2e-gallery-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('e2e-gallery-test', async function() {
    await driver.get("https://chatbot-gallery-staging.web.app/emulator?gallery=5f222d5dd3678600079eafeb");
    await driver.manage().window().setRect(889, 807);
    const header = await driver.wait(until.elementLocated(By.xpath("//div[2]/div/h4")),5000).getText();
    assert(header == 'Section Two');
  })
})
