version: 2.1
jobs:
  build-api:
    docker:
      - image: direqteng/gcpbuildenv
        environment:
          # Add app engine sdk to pythonpath for local unit tests.
          GCP_SDK_PATH: /usr/lib/google-cloud-sdk
          PYTHONPATH: /usr/lib/google-cloud-sdk/platform/google_appengine
          GCLOUD_PROJECT: "bill-deploytest"
          TERM: xterm-256color
    steps:
      - checkout
      - run:
          name: CheckChangedFolders
          command: |
            LAST_COMMIT=$(git rev-parse HEAD~1)
            API_CHANGED=$(git diff --name-only $LAST_COMMIT..HEAD | grep -i -v -E '^functions/')
            echo $API_CHANGED
            if [ -z "$API_CHANGED" ]; then
              echo "api not updated, nothing to build."
              echo "circleci-agent step halt"
            fi
      - run:
          name: SetEnvVars
          command: |
            # echo $CLIENT_SECRET | base64 --decode -i > ${HOME}/client-secret.json
            echo $PYTHONPATH
            echo $GLOBAL_SECRET | base64 --decode -i > ${HOME}/client-secret.json
            sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
      - run:
          name: BuildApi
          command: |
            echo "building api"
      - run:
          name: LocalTest
          command: |
            # run local unit tests
            # python test_main.py
      - deploy:
          name: Deploy Master to GCP
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "deploy api"
            fi
      - run:
          name: Cleanup on Error
          when: on_fail
          command: |
            echo "$NEW_VER_DEPLOYED"
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "$NEW_VER_DEPLOYED" != "true" ]; then
              # Make sure this version is deleted if there's an error
              echo "gcloud -q app versions delete ${CIRCLE_BUILD_NUM}"
            fi
  build-functions:
    docker:
      - image: direqteng/gcpbuildenv
        environment:
          GCLOUD_PROJECT: "bill-deploytest"
    steps:
      - checkout
      - run:
          name: CheckChangedFolders
          command: |
            LAST_COMMIT=$(git rev-parse HEAD~1)
            FUNCTIONS_CHANGED=$(git diff --name-only $LAST_COMMIT..HEAD | grep -i -E '^functions/')
            echo $FUNCTIONS_CHANGED
            if [ -z "$FUNCTIONS_CHANGED" ]; then
              echo "api not updated, nothing to build."
              circleci-agent step halt
            fi
      - run:
          name: BuildFunctions
          command: |
            echo "building functions"
      - deploy:
          name: DeployFunctions
          command: |
            echo "deploying functions"        

workflows:
  version: 2
  build-all:
    jobs:
      - build-api
      - build-functions
