version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: direqteng/gcpbuildenv
        environment:
          # Add app engine sdk to pythonpath for local unit tests.
          PYTHONPATH: /usr/lib/google-cloud-sdk/platform/google_appengine
          GCLOUD_PROJECT: "bill-deploytest"
          TERM: xterm-256color
      - image: selenium/standalone-chrome:3.11.0
    steps:
      - checkout
      - run:
          name: SetEnvVars
          command: |
            # echo $GCP_CONSOLE_SVC_ACCOUNT | base64 --decode -i > ${HOME}/client-secret.json
            # authenticate and configure gcloud project
            # gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
            gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Build and Deploy to Staging
          command: |
            npm install
            npm run deploy-staging
      - run:
          name: Install protractor
          command: |
            npm install -g protractor
            webdriver-manager update
      - run:
          name: Test on staging
          command: |
            npm run test-staging
      - run:
          name: Deploy prod and sanity test
          command: |
            # npm run deploy
            # npm run test-prod
      - run:
          name: Cleanup on Error
          when: on_fail
          command: |
            # Make sure the new version is deleted if there's an error before deployment
            # Temporarily remove so that we can manually test deployment
            # gcloud -q app versions delete ${CIRCLE_BUILD_NUM}
