version: 2.1
jobs:
  checkout:
    docker:
      - image: direqteng/gcpbuildenv
        environment:
          # Add app engine sdk to pythonpath for local unit tests.
          GCP_SDK_PATH: /usr/lib/google-cloud-sdk
          PYTHONPATH: /usr/lib/google-cloud-sdk/platform/google_appengine
          GCLOUD_PROJECT: "bill-deploytest"
    steps:
      - checkout
      - run:
          name: CheckChangedFolders
          command: |
            API_CHANGED=$(git diff --name-only origin/master..HEAD | grep -i -v -E '^functions/')
            echo 'export API_CHANGED=$API_CHANGED' >> $BASH_ENV
            FUNCTIONS_CHANGED=$(git diff --name-only origin/master..HEAD | grep -i -E '^functions/')
            echo 'export FUNCTIONS_CHANGED=$FUNCTIONS_CHANGED' >> $BASH_ENV
  build-api:
      - run:
          name: SetEnvVars
          command: |
            if [ -z "$API_CHANGED" ]; then
              echo "api not updated, nothing to build."
              circleci-agent step halt
            fi

            # echo $CLIENT_SECRET | base64 --decode -i > ${HOME}/client-secret.json
            echo $PYTHONPATH
            echo $GLOBAL_SECRET | base64 --decode -i > ${HOME}/client-secret.json
            sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
      - run:
          name: BuildApi
          command: |
            echo "building api"
      - run:
          name: LocalTest
          command: |
            # run local unit tests
            # python test_main.py
      - deploy:
          name: Deploy Master to GCP
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "deploy api"
            fi
      - run:
          name: Cleanup on Error
          when: on_fail
          command: |
            echo "$NEW_VER_DEPLOYED"
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "$NEW_VER_DEPLOYED" != "true" ]; then
              # Make sure this version is deleted if there's an error
              gcloud -q app versions delete ${CIRCLE_BUILD_NUM}
            fi
  build-functions:
    - run:
      name: BuildFunctions
      command: |
        if [ -z "$FUNCTIONS_CHANGED" ]; then
          echo "api not updated, nothing to build."
          circleci-agent step halt
        fi

        echo "building functions"
    - run:
      name: DeployFunctions
      command: |
        echo "deploying functions"        


workflows:
  version: 2
  checkout:
    jobs:
      - checkout:
  build:
    jobs:
      - build-api:
        requires:
          - checkout
      - build-functions:
        requires:
          - checkout
