version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
        environment:
          # Add app engine sdk to pythonpath for local unit tests.
          PYTHONPATH: /usr/lib/google-cloud-sdk/platform/google_appengine
          GCLOUD_PROJECT: "bill-deploytest"
    steps:
      - checkout
      - run:
          name: SetEnvVars
          command: |
            echo $CLIENT_SECRET | base64 --decode -i > ${HOME}/client-secret.json
            sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
      - run:
          name: PythonEnv
          command: |
            mkdir -p lib
            pip install -r requirements.txt -t lib
            # authenticate and configure gcloud project
            gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
            gcloud config set project $GCLOUD_PROJECT
      - run:
          name: LocalTest
          command: |
            # run local unit tests
            python test_main.py
      - deploy:
          name: Deploy Master to GCP
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploy to AppEngine
              gcloud -q app deploy app.yaml --no-promote --version=${CIRCLE_BUILD_NUM}
              # Run our E2E Test against the latest version
              python e2e_test.py ${CIRCLE_BUILD_NUM}
              # If OK, promote latest version
              gcloud -q app services set-traffic --splits ${CIRCLE_BUILD_NUM}=1
            fi